export enum ErrorContext {
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  CREATE_FUNCTIONARY = 'CREATE_FUNCTIONARY',
  CREATE_CUSTOMER = 'CREATE_CUSTOMER',
  CREATE_TRANSACTION = 'CREATE_TRANSACTION',
  UPDATE_BANK_ACCOUNT_TYPE = 'UPDATE_BANK_ACCOUNT_TYPE',
  GET_DATA_BY_CPF = 'GET_DATA_BY_CPF',
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  TRANSFER = 'TRANSFER',
}
